#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
import time

print("test_move :: START...")

def infiniteTalk():
    # Initialize ROS node with ROS client
    rclpy.init()
    aNode= Node( "simple_move_order" )
    talker= ROSTalker(aNode)
    # Start infinite loop
    rclpy.spin(aNode)
    # Clean everything and switch the light off
    aNode.destroy_node()
    rclpy.shutdown()

class ROSTalker:
    def __init__(self, rosNode):
        self._publisher= rosNode.create_publisher(Twist, '/multi/cmd_nav', 10 )
        self._timer = rosNode.create_timer(9, self.timer_callback)
        self._i = 0

    def timer_callback(self):
        velocity = Twist()
        # Feed Twist velocity values
        velocity.linear.x = 0.0
        velocity.linear.y = 0.0
        velocity.linear.z = 0.0

        velocity.angular.x = 0.0
        velocity.angular.y = 0.0
        velocity.angular.z = 0.0

        # Publish 
        self._publisher.publish(velocity)

        for i in range(10):
            velocity.linear.x += 0.05
            self._publisher.publish(velocity)
            time.sleep(0.1)

        for i in range(10):
            velocity.linear.x -= 0.05
            self._publisher.publish(velocity)
            time.sleep(0.1)

        velocity.linear.x = 0.0
        velocity.angular.z = 1.0
        self._publisher.publish(velocity)
        time.sleep(0.5)

        velocity.angular.z = -1.0
        self._publisher.publish(velocity)
        time.sleep(0.5)

        velocity.angular.z = -1.0
        self._publisher.publish(velocity)
        time.sleep(0.5)

        velocity.angular.z = 1.0
        self._publisher.publish(velocity)
        time.sleep(0.5)

        velocity.angular.z = 0.0
        for i in range(10):
            velocity.linear.x -= 0.05
            self._publisher.publish(velocity)
            time.sleep(0.1)

        for i in range(10):
            velocity.linear.x += 0.05
            self._publisher.publish(velocity)
            time.sleep(0.1)

        velocity.linear.x = 0.0
        velocity.angular.z = 1.0
        self._publisher.publish(velocity)
        time.sleep(0.5)

        velocity.angular.z = -1.0
        self._publisher.publish(velocity)
        time.sleep(0.5)

        velocity.angular.z = -1.0
        self._publisher.publish(velocity)
        time.sleep(0.5)

        velocity.angular.z = 1.0
        self._publisher.publish(velocity)
        time.sleep(0.5)


# Execute the function.
if __name__ == "__main__":
    infiniteTalk()